"""
guided_trace_writer.py - Write live step trace to markdown and JSON.

Outputs:
  artifacts/live_interactive_trace.md   — human-readable live trace
  artifacts/live_interactive_trace.json — machine-readable trace

Written incrementally — each step is appended immediately.
Includes: step number, screen, action, evidence, screenshots, verdict.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from qa_ai.interactive_runtime.schemas import (
    AIVerdict,
    GuidedStep,
)

logger = logging.getLogger(__name__)

_VERDICT_EMOJI = {
    AIVerdict.PASS: "✅",
    AIVerdict.FAIL: "❌",
    AIVerdict.UNCLEAR: "⚠️",
}


class GuidedTraceWriter:
    """
    Write guided test trace incrementally.

    Call start() before first step, add_step() for each step,
    and finish() to write summary and close.
    """

    def __init__(
        self,
        output_dir: str = "artifacts",
        write_markdown: bool = True,
        write_json: bool = True,
    ):
        self._out = Path(output_dir)
        self._out.mkdir(parents=True, exist_ok=True)
        self._write_md = write_markdown
        self._write_json = write_json
        self._steps: List[GuidedStep] = []
        self._md_path = self._out / "live_interactive_trace.md"
        self._json_path = self._out / "live_interactive_trace.json"
        self._started = False
        self._session_id: str = ""

    def start(self, app_name: str, test_objective: str, session_id: str = "") -> None:
        """Initialize trace files with header."""
        self._session_id = session_id
        self._started = True

        if self._write_md:
            header = (
                f"# Inspectra Live Guided Trace\n\n"
                f"**App:** {app_name}  \n"
                f"**Objective:** {test_objective}  \n"
                f"**Started:** {datetime.now(timezone.utc).isoformat()}  \n"
                f"**Session:** {session_id}  \n\n"
                f"---\n\n"
            )
            self._md_path.write_text(header, encoding="utf-8")

        if self._write_json:
            self._json_path.write_text(json.dumps({
                "session_id": session_id,
                "app_name": app_name,
                "test_objective": test_objective,
                "started_at": datetime.now(timezone.utc).isoformat(),
                "steps": [],
            }, indent=2), encoding="utf-8")

    def add_step(self, step: GuidedStep) -> None:
        """Append a completed step to the trace."""
        self._steps.append(step)

        if self._write_md:
            self._append_md_step(step)

        if self._write_json:
            self._rewrite_json()

    def finish(
        self,
        total_pass: int = 0,
        total_fail: int = 0,
        total_unclear: int = 0,
    ) -> None:
        """Write summary section and close trace."""
        if self._write_md:
            summary = (
                f"\n---\n\n"
                f"## Summary\n\n"
                f"| Verdict | Count |\n"
                f"|---------|-------|\n"
                f"| ✅ PASS | {total_pass} |\n"
                f"| ❌ FAIL | {total_fail} |\n"
                f"| ⚠️ UNCLEAR | {total_unclear} |\n"
                f"| **Total** | **{len(self._steps)}** |\n\n"
                f"*Generated by Inspectra QA-AI — {datetime.now(timezone.utc).isoformat()}*\n"
            )
            with open(self._md_path, "a", encoding="utf-8") as f:
                f.write(summary)

        if self._write_json:
            self._rewrite_json(
                summary={
                    "total_steps": len(self._steps),
                    "pass": total_pass,
                    "fail": total_fail,
                    "unclear": total_unclear,
                    "finished_at": datetime.now(timezone.utc).isoformat(),
                }
            )

    def _append_md_step(self, step: GuidedStep) -> None:
        emoji = _VERDICT_EMOJI.get(step.final_verdict, "?")
        lines = [
            f"## Step {step.step_number:03d} — {step.screen_title}\n",
            f"**Verdict:** {emoji} {step.final_verdict.value.upper()}  "
            f"**Confidence:** {step.confidence_pct:.0f}%  \n",
        ]

        if step.plan:
            lines.append(f"**Plan:** {step.plan}  \n")
        if step.why:
            lines.append(f"**Why:** {step.why}  \n")
        if step.permission_needed:
            lines.append(f"**Permission:** {step.permission_needed}  \n")
        if step.action_taken:
            lines.append(f"**Action:** {step.action_taken}  \n")

        if step.evidence_checked:
            lines.append("\n**Evidence Checked:**\n")
            for ev in step.evidence_checked:
                lines.append(f"- {ev}\n")

        if step.log_matches:
            lines.append("\n**Log Matches:**\n")
            for m in step.log_matches:
                lines.append(f"- `{m[:100]}`\n")

        if step.db_check_result:
            lines.append(f"\n**DB Check:** {step.db_check_result}\n")

        if step.backend_check_result:
            lines.append(f"\n**Backend Check:** {step.backend_check_result}\n")

        if step.screenshot_before:
            lines.append(f"\n**Screenshot Before:** `{step.screenshot_before}`\n")
        if step.screenshot_after:
            lines.append(f"**Screenshot After:** `{step.screenshot_after}`\n")

        if step.oracle_suggestion:
            o = step.oracle_suggestion
            lines.append(
                f"\n**Oracle Suggestion:** {o.suggested_verdict.value.upper()} "
                f"(confidence {o.confidence:.0%}) — {o.reasoning[:120]}\n"
            )

        if step.grounded_verdict:
            gv = step.grounded_verdict
            lines.append(f"\n**Grounded Reasoning:** {gv.reasoning[:200]}\n")
            if gv.evidence_sources_missing:
                missing = ", ".join(gv.evidence_sources_missing[:4])
                lines.append(f"**Evidence Missing:** {missing}\n")
            if gv.next_best_check:
                lines.append(f"**Next Check:** {gv.next_best_check}\n")

        lines.append("\n---\n\n")

        with open(self._md_path, "a", encoding="utf-8") as f:
            f.writelines(lines)

    def _rewrite_json(self, summary: Optional[Dict[str, Any]] = None) -> None:
        data: Dict[str, Any] = {}
        if self._json_path.exists():
            try:
                data = json.loads(self._json_path.read_text(encoding="utf-8"))
            except Exception:
                data = {}

        data["steps"] = [self._step_to_dict(s) for s in self._steps]
        if summary:
            data["summary"] = summary

        self._json_path.write_text(
            json.dumps(data, indent=2, default=str), encoding="utf-8"
        )

    @staticmethod
    def _step_to_dict(step: GuidedStep) -> Dict[str, Any]:
        d = step.model_dump()
        # Ensure nested models are serialized
        if step.oracle_suggestion:
            d["oracle_suggestion"] = step.oracle_suggestion.model_dump()
        if step.grounded_verdict:
            d["grounded_verdict"] = step.grounded_verdict.model_dump()
        return d
