"""
qa_ai/schemas/__init__.py - Schema package initialization.
Exports all Pydantic models for clean imports.
"""

from qa_ai.schemas.app_map_schema import (
    AppMap,
    StackInfo,
    StackCapabilities,
    APIEndpoint,
    APIRisk,
    Screen,
    CriticalFlow,
    SecuritySurfaces,
    Testability,
    AppMapMetadata,
)
from qa_ai.schemas.test_plan_schema import (
    TestPlan,
    TestCase,
    TestType,
    Priority,
    RiskLevel,
    TestPlanMetadata,
    TestPlanSummary,
    TestSuites,
)
from qa_ai.schemas.finding_schema import (
    Finding,
    FindingSet,
    FindingSeverity,
    FindingCategory,
    FindingStatus,
    EvidenceRef,
)
from qa_ai.schemas.execution_result_schema import (
    ExecutionResult,
    TestResult,
    SuiteResult,
    TestOutcome,
    ExecutionMetadata,
)
from qa_ai.schemas.audit_result_schema import (
    AuditResult,
    AuditCheck,
    AuditCheckStatus,
    AuditSeverity,
    AuditResultMetadata,
)
from qa_ai.schemas.reporting_schema import (
    ArtifactMetadata,
    ArtifactContract,
    ImprovementBacklogItem,
    ImprovementBacklogArtifact,
    AuditSummaryArtifact,
    RiskVisualizationArtifact,
    WorkflowVisualizationArtifact,
    TraceVisualizationArtifact,
    GraphVisualizationArtifact,
)
from qa_ai.schemas.improvement_schema import (
    SoftwareHealthScoreArtifact,
    FixPlanArtifact,
    RemediationPlanArtifact,
    RetestResultsArtifact,
    QualityTrendArtifact,
    RegressionGuardReportArtifact,
    LearningRegistryArtifact,
    ChangeImpactAnalysisArtifact,
)
from qa_ai.schemas.runtime_schema import (
    ExecutionTraceArtifact,
    NetworkTraceArtifact,
    ReplayAnalysisArtifact,
)
from qa_ai.schemas.evidence_schema import (
    EvidenceGraphArtifact,
    EvidenceGraphData,
    EvidenceGraphNode,
)
from qa_ai.schemas.runtime_lab_schema import (
    BootstrapPlanArtifact,
    DockerRuntimePlanArtifact,
    RuntimeMonitorReportArtifact,
    LiveBenchmarkSummaryArtifact,
    LiveBenchmarkMetricsArtifact,
    CleanupReportArtifact,
    RuntimeLabDoctorArtifact,
)
from qa_ai.schemas.distributed_runtime_schema import (
    ActorRegistryArtifact,
    MultiSessionReportArtifact,
    ConcurrencyAnalysisArtifact,
    NetworkConditionReportArtifact,
    OfflineRecoveryReportArtifact,
    SyncConflictReportArtifact,
    ChaosExecutionReportArtifact,
    DistributedRuntimeReportArtifact,
    DistributedEvidenceGraphArtifact,
)
from qa_ai.schemas.mobile_runtime_schema import (
    DeviceRegistryArtifact,
    AndroidEmulatorReportArtifact,
    IosSimulatorReportArtifact,
    FlutterExecutionPlanArtifact,
    AppiumPlanArtifact,
    MaestroPlanArtifact,
    DeviceSessionReportArtifact,
    MobileNetworkReportArtifact,
    MobileRuntimeMonitorReportArtifact,
    MobileLogsIndexArtifact,
    MobileEvidenceGraphArtifact,
    MobileRuntimeReportArtifact,
)
from qa_ai.schemas.ai_reasoning_schema import (
    ReasoningContextArtifact,
    SemanticRootCauseAnalysisArtifact,
    AdaptiveAuditPlanArtifact,
    EvidenceSynthesisArtifact,
    SemanticRiskReportArtifact,
    AIGeneratedScenariosArtifact,
    AIFixReasoningArtifact,
    LearningOptimizationReportArtifact,
    AIReasoningSummaryArtifact,
)
from qa_ai.schemas.remediation_schema import (
    PatchProposalsArtifact,
    ChangeSimulationReportArtifact,
    RollbackPlanArtifact,
    RemediationRetestScopeArtifact,
    RemediationRiskReportArtifact,
    RemediationValidationReportArtifact,
    RemediationApprovalLogArtifact,
    RemediationSummaryArtifact,
)
from qa_ai.schemas.remediation_runtime_schema import (
    RuntimePatchProposalsArtifact,
    RemediationChangeSimulationArtifact,
    RemediationRollbackPlanArtifact,
    RemediationSandboxReportArtifact,
    RemediationApprovalWorkflowArtifact,
    RemediationRetestScopeRuntimeArtifact,
    RemediationValidationRuntimeArtifact,
    RemediationAuditLogArtifact,
    RemediationRuntimeSummaryArtifact,
)
from qa_ai.schemas.cicd_schema import (
    CICDProviderReportArtifact,
    CIWorkflowPlanArtifact,
    IncrementalAuditPlanArtifact,
    BaselineComparisonArtifact,
    ReleaseGateDecisionArtifact,
    CICDAuditReportArtifact,
)
from qa_ai.schemas.cicd_runtime_schema import (
    CICDRuntimeProviderReportArtifact,
    GitHubActionsPlanArtifact,
    GitLabCIPlanArtifact,
    JenkinsPipelinePlanArtifact,
    IncrementalAuditRuntimePlanArtifact,
    BaselineComparisonRuntimeReportArtifact,
    ReleaseGateRuntimeDecisionArtifact,
    PipelinePolicyRuntimeReportArtifact,
    PRAuditRuntimeReportArtifact,
    CICDRuntimeSummaryArtifact,
    CICDAuditLogArtifact,
)
from qa_ai.schemas.platform_performance_schema import (
    PerformanceProfileArtifact,
    WorkflowTimingReportArtifact,
    ArtifactCacheReportArtifact,
    ArtifactLifecyclePlanArtifact,
    EvidenceStorageReportArtifact,
    IncrementalGraphPlanArtifact,
    ParallelExecutionPlanArtifact,
    MemoryUsageReportArtifact,
    ScalabilityReportArtifact,
)
from qa_ai.schemas.enterprise_schema import (
    WorkspaceRegistryArtifact,
    ProjectRegistryArtifact,
    TeamRegistryArtifact,
    RoleAccessReportArtifact,
    GovernancePolicyReportArtifact,
    AuditHistoryIndexArtifact,
    GovernanceSummaryArtifact,
    GovernanceAccessLogArtifact,
    EnterpriseRuntimeSummaryArtifact,
)
from qa_ai.schemas.benchmark_intelligence_schema import (
    BenchmarkDatasetRegistryArtifact,
    BenchmarkScoringReportArtifact,
    FalsePositiveReportArtifact,
    BenchmarkCoverageTrendArtifact,
    BenchmarkComparisonReportArtifact,
    BenchmarkMaturityScoreArtifact,
    BenchmarkHistoryIndexArtifact,
    BenchmarkIntelligenceSummaryArtifact,
    BenchmarkRuntimeSummaryArtifact,
)
from qa_ai.schemas.self_optimization_schema import (
    AuditMemoryIndexArtifact,
    StrategyAdaptationPlanArtifact,
    FindingDeduplicationReportArtifact,
    ConfidenceCalibrationReportArtifact,
    EvidenceQualityOptimizationArtifact,
    ScenarioOptimizationReportArtifact,
    RiskPredictionReportArtifact,
    RemediationLearningReportArtifact,
    CrossProjectLearningReportArtifact,
    SelfOptimizationSummaryArtifact,
)
from qa_ai.schemas.ai_orchestration_schema import (
    SoftwareUnderstandingArtifact,
    AIAuditStrategyArtifact,
    TestIntentsArtifact,
    IntelligentScenarioPlanArtifact,
    EvidenceInterpretationArtifact,
    AIRCACoordinationArtifact,
    AIImprovementStrategyArtifact,
    AIDecisionLogArtifact,
    AIConfidenceReportArtifact,
    AIAuditBrainSummaryArtifact,
)
from qa_ai.schemas.model_routing_schema import (
    ModelUsageLogArtifact,
    ModelRoutingReportArtifact,
)

__all__ = [
    # App Map
    "AppMap",
    "StackInfo",
    "StackCapabilities",
    "APIEndpoint",
    "APIRisk",
    "Screen",
    "CriticalFlow",
    "SecuritySurfaces",
    "Testability",
    "AppMapMetadata",
    # Test Plan
    "TestPlan",
    "TestCase",
    "TestType",
    "Priority",
    "RiskLevel",
    "TestPlanMetadata",
    "TestPlanSummary",
    "TestSuites",
    # Findings
    "Finding",
    "FindingSet",
    "FindingSeverity",
    "FindingCategory",
    "FindingStatus",
    "EvidenceRef",
    # Execution Results
    "ExecutionResult",
    "TestResult",
    "SuiteResult",
    "TestOutcome",
    "ExecutionMetadata",
    # Audit Results
    "AuditResult",
    "AuditCheck",
    "AuditCheckStatus",
    "AuditSeverity",
    "AuditResultMetadata",
    # Artifact Contracts
    "ArtifactMetadata",
    "ArtifactContract",
    "ImprovementBacklogItem",
    "ImprovementBacklogArtifact",
    "AuditSummaryArtifact",
    "RiskVisualizationArtifact",
    "WorkflowVisualizationArtifact",
    "TraceVisualizationArtifact",
    "GraphVisualizationArtifact",
    "SoftwareHealthScoreArtifact",
    "FixPlanArtifact",
    "RemediationPlanArtifact",
    "RetestResultsArtifact",
    "QualityTrendArtifact",
    "RegressionGuardReportArtifact",
    "LearningRegistryArtifact",
    "ChangeImpactAnalysisArtifact",
    "ExecutionTraceArtifact",
    "NetworkTraceArtifact",
    "ReplayAnalysisArtifact",
    "EvidenceGraphArtifact",
    "EvidenceGraphData",
    "EvidenceGraphNode",
    # Runtime Lab
    "BootstrapPlanArtifact",
    "DockerRuntimePlanArtifact",
    "RuntimeMonitorReportArtifact",
    "LiveBenchmarkSummaryArtifact",
    "LiveBenchmarkMetricsArtifact",
    "CleanupReportArtifact",
    "RuntimeLabDoctorArtifact",
    # Distributed Runtime
    "ActorRegistryArtifact",
    "MultiSessionReportArtifact",
    "ConcurrencyAnalysisArtifact",
    "NetworkConditionReportArtifact",
    "OfflineRecoveryReportArtifact",
    "SyncConflictReportArtifact",
    "ChaosExecutionReportArtifact",
    "DistributedRuntimeReportArtifact",
    "DistributedEvidenceGraphArtifact",
    # Mobile Runtime
    "DeviceRegistryArtifact",
    "AndroidEmulatorReportArtifact",
    "IosSimulatorReportArtifact",
    "FlutterExecutionPlanArtifact",
    "AppiumPlanArtifact",
    "MaestroPlanArtifact",
    "DeviceSessionReportArtifact",
    "MobileNetworkReportArtifact",
    "MobileRuntimeMonitorReportArtifact",
    "MobileLogsIndexArtifact",
    "MobileEvidenceGraphArtifact",
    "MobileRuntimeReportArtifact",
    # AI Reasoning
    "ReasoningContextArtifact",
    "SemanticRootCauseAnalysisArtifact",
    "AdaptiveAuditPlanArtifact",
    "EvidenceSynthesisArtifact",
    "SemanticRiskReportArtifact",
    "AIGeneratedScenariosArtifact",
    "AIFixReasoningArtifact",
    "LearningOptimizationReportArtifact",
    "AIReasoningSummaryArtifact",
    # Controlled Remediation
    "PatchProposalsArtifact",
    "ChangeSimulationReportArtifact",
    "RollbackPlanArtifact",
    "RemediationRetestScopeArtifact",
    "RemediationRiskReportArtifact",
    "RemediationValidationReportArtifact",
    "RemediationApprovalLogArtifact",
    "RemediationSummaryArtifact",
    "RuntimePatchProposalsArtifact",
    "RemediationChangeSimulationArtifact",
    "RemediationRollbackPlanArtifact",
    "RemediationSandboxReportArtifact",
    "RemediationApprovalWorkflowArtifact",
    "RemediationRetestScopeRuntimeArtifact",
    "RemediationValidationRuntimeArtifact",
    "RemediationAuditLogArtifact",
    "RemediationRuntimeSummaryArtifact",
    # CI/CD Continuous Audit
    "CICDProviderReportArtifact",
    "CIWorkflowPlanArtifact",
    "IncrementalAuditPlanArtifact",
    "BaselineComparisonArtifact",
    "ReleaseGateDecisionArtifact",
    "CICDAuditReportArtifact",
    "CICDRuntimeProviderReportArtifact",
    "GitHubActionsPlanArtifact",
    "GitLabCIPlanArtifact",
    "JenkinsPipelinePlanArtifact",
    "IncrementalAuditRuntimePlanArtifact",
    "BaselineComparisonRuntimeReportArtifact",
    "ReleaseGateRuntimeDecisionArtifact",
    "PipelinePolicyRuntimeReportArtifact",
    "PRAuditRuntimeReportArtifact",
    "CICDRuntimeSummaryArtifact",
    "CICDAuditLogArtifact",
    # Platform Performance
    "PerformanceProfileArtifact",
    "WorkflowTimingReportArtifact",
    "ArtifactCacheReportArtifact",
    "ArtifactLifecyclePlanArtifact",
    "EvidenceStorageReportArtifact",
    "IncrementalGraphPlanArtifact",
    "ParallelExecutionPlanArtifact",
    "MemoryUsageReportArtifact",
    "ScalabilityReportArtifact",
    # Enterprise Governance
    "WorkspaceRegistryArtifact",
    "ProjectRegistryArtifact",
    "TeamRegistryArtifact",
    "RoleAccessReportArtifact",
    "GovernancePolicyReportArtifact",
    "AuditHistoryIndexArtifact",
    "GovernanceSummaryArtifact",
    "GovernanceAccessLogArtifact",
    "EnterpriseRuntimeSummaryArtifact",
    # Benchmark Intelligence
    "BenchmarkDatasetRegistryArtifact",
    "BenchmarkScoringReportArtifact",
    "FalsePositiveReportArtifact",
    "BenchmarkCoverageTrendArtifact",
    "BenchmarkComparisonReportArtifact",
    "BenchmarkMaturityScoreArtifact",
    "BenchmarkHistoryIndexArtifact",
    "BenchmarkIntelligenceSummaryArtifact",
    "BenchmarkRuntimeSummaryArtifact",
    # Self-Optimization
    "AuditMemoryIndexArtifact",
    "StrategyAdaptationPlanArtifact",
    "FindingDeduplicationReportArtifact",
    "ConfidenceCalibrationReportArtifact",
    "EvidenceQualityOptimizationArtifact",
    "ScenarioOptimizationReportArtifact",
    "RiskPredictionReportArtifact",
    "RemediationLearningReportArtifact",
    "CrossProjectLearningReportArtifact",
    "SelfOptimizationSummaryArtifact",
    # AI Orchestration
    "SoftwareUnderstandingArtifact",
    "AIAuditStrategyArtifact",
    "TestIntentsArtifact",
    "IntelligentScenarioPlanArtifact",
    "EvidenceInterpretationArtifact",
    "AIRCACoordinationArtifact",
    "AIImprovementStrategyArtifact",
    "AIDecisionLogArtifact",
    "AIConfidenceReportArtifact",
    "AIAuditBrainSummaryArtifact",
    "ModelUsageLogArtifact",
    "ModelRoutingReportArtifact",
]
